### ISSUE TITLE
fsharp.formatting.commandtool is deprecated

### ISSUE THREAD

**Issue by 64J0** [fslaborg/fslaborg.github.io#42]
## Description:

The package `fsharp.formatting.commandtool` is deprecated according to its [NuGet page](https://www.nuget.org/packages/FSharp.Formatting.CommandTool/). We need to update this `.config/dotnet-tools.json` to start using the new package instead.

**Comment by 64J0** [comment]
Also, I'm getting this error when trying to install this package with dotnet-core 3.1 as mentioned in the README:

```
error NU1202: Package FSharp.Formatting.CommandTool 11.4.4 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package FSharp.Formatting.CommandTool 11.4.4 supports: net5.0 (.NETCoreApp,Version=v5.0) / any

Package "fsharp.formatting.commandtool" failed to restore, due to Microsoft.DotNet.ToolPackage.ToolPackageException: The tool package could not be restored.
   at Microsoft.DotNet.Tools.Tool.Install.ProjectRestorer.Restore(FilePath project, PackageLocation packageLocation, String verbosity)
   at Microsoft.DotNet.ToolPackage.ToolPackageInstaller.InstallPackageToExternalManagedLocation(PackageLocation packageLocation, PackageId packageId, VersionRange versionRange, String targetFramework, String verbosity)
   at Microsoft.DotNet.Tools.Tool.Restore.ToolRestoreCommand.InstallPackages(ToolManifestPackage package, Nullable`1 configFile)
```

I'll do other tests with dotnet 5 to check if it works.

**Comment by 64J0** [comment]
With dotnet 5 it worked, I'll update in this PR: https://github.com/fslaborg/fslaborg.github.io/pull/39

**Comment by Freymaurer** [comment]
Fixed, or will be obsolete with upcoming changes!
